In [18]:
##-- Испольлзуемые библиотеки
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import StandardScaler

In [19]:
##############--TEST--#########
# X = np.array([[1,2], [3, 4], [5, 6]])
# y = np.array([0, 1, 0])
# clf = Perceptron()
# clf.fit(X, y)
# predictions=clf.predict(X)
# predictions

# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# X_train = np.array([[100.0, 2.0], [50.0, 4.0], [70.0, 6.0]])
# X_test = np.array([[90.0, 1], [40.0, 3], [60.0, 4]])
# X_train_scaled = scaler.fit_transform(X_train)
# print(X_train_scaled)
# X_test_scaled = scaler.transform(X_test)
# X_test_scaled

In [22]:
data_train = pd.read_csv('perceptron-train.csv')
data_train

     -1.0  -0.0246259814315  1174.60023796
0     1.0         -0.978058    1083.198803
1    -1.0          0.314272   -1472.977609
2    -1.0          0.179752     231.017267
3     1.0         -1.262544    -778.271726
4    -1.0          0.249970     -52.801483
..    ...               ...            ...
294  -1.0         -0.126438    1861.564124
295  -1.0         -0.490972    1815.652064
296   1.0         -0.375750    -314.074374
297   1.0         -1.861976   -1083.677679
298   1.0         -0.039329   -1863.884299

[299 rows x 3 columns]

In [23]:
data_test = pd.read_csv('perceptron-test.csv')
data_test

     -1.0  1.6514365371  1337.45382564
0     1.0     -0.866495    1191.232457
1    -1.0      0.789828    -475.647768
2    -1.0      0.179549    1959.095353
3     1.0     -0.434351     568.504207
4     1.0     -1.506295     929.584470
..    ...           ...            ...
194  -1.0      1.150206    2559.850231
195   1.0     -0.732462     159.748695
196   1.0      0.412912   -1587.206427
197  -1.0     -0.098685     682.034777
198   1.0      0.760949   -1577.448794

[199 rows x 3 columns]